pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('ai-weather-app') {
                    bat 'npm install --legacy-peer-deps'
                }
            }
        }

        stage('Build React App') {
            steps {
                dir('ai-weather-app') {
                    bat 'npm run build'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('ai-weather-app') {
                    bat 'docker build -t ai-weather-app .'
                }
            }
        }

    }
}